#该文件需保存为UTF-8格式
spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-ycyoes-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-ycyoes-test